# Generated by Django 3.2 on 2023-09-30 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='FavoriteRestaurant',
        ),
        migrations.RenameField(
            model_name='favoriterestaurant',
            old_name='item',
            new_name='restaurant',
        ),
    ]
