# Generated by Django 3.2.4 on 2024-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_ordercomment_waitercomment_waiterrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='image',
            field=models.ImageField(upload_to='restaurant/image/'),
        ),
    ]
