# Generated by Django 3.2.4 on 2024-04-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurantmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='service_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Service charge percentage', max_digits=4),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurantmodel')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'restaurants_category',
            },
        ),
        migrations.AlterField(
            model_name='dish',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.category'),
        ),
    ]