# Generated by Django 3.2.4 on 2024-06-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
