# Generated by Django 3.2.4 on 2024-06-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_waitermodel_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitermodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waitermodel',
            name='updated_at',
        ),
    ]
